"""添加级联删除约束

Revision ID: 1fff349a3aec
Revises: 8a1eacd53da8
Create Date: 2025-05-18 18:33:44.515468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fff349a3aec'
down_revision = '8a1eacd53da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.drop_constraint('post_views_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('post_views_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_views_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('post_views_ibfk_1', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
